import { PermissionCodes } from '@/config/permissionCodes'

export const menuList = [
  {
    name: '股票池',
    foldName: '股票池',
    icon: 'Box',
    path: '/stock-pool',
    children: [
      {
        name: '策略股票池',
        foldName: '策略股票池',
        path: '/stock-pool/strategy',
        permissionCodes: [PermissionCodes.STOCK_POOL_STRATEGY_READ],
      },
      {
        name: '自选分组股票池',
        foldName: '自选分组股票池',
        path: '/stock-pool/self-selected',
        permissionCodes: [PermissionCodes.STOCK_POOL_SELF_SELECTED_READ],
      },
      {
        name: '买入监控',
        foldName: '买入监控',
        path: '/stock-pool/buy-signal',
        permissionCodes: [PermissionCodes.STRATEGY_SIGNAL_READ],
      },
      {
        name: '卖出信号股票池',
        foldName: '卖出信号股票池',
        path: '/stock-pool/sell-signal',
        permissionCodes: [PermissionCodes.STRATEGY_SIGNAL_READ],
      },
    ],
  },
  {
    name: '信号策略',
    foldName: '信号策略',
    icon: 'DataAnalysis',
    path: '/trading-strategy/signal-strategies',
    permissionCodes: [PermissionCodes.STRATEGY_SIGNAL_READ],
    children: [
      {
        name: '买点策略',
        foldName: '买点策略',
        path: '/trading-strategy/signal-strategies/buy',
        permissionCodes: [PermissionCodes.STRATEGY_SIGNAL_READ],
      },
      {
        name: '卖点策略',
        foldName: '卖点策略',
        path: '/trading-strategy/signal-strategies/sell',
        permissionCodes: [PermissionCodes.STRATEGY_SIGNAL_READ],
      },
      {
        name: '买卖通用策略',
        foldName: '通用策略',
        path: '/trading-strategy/signal-strategies/common',
        permissionCodes: [PermissionCodes.STRATEGY_SIGNAL_READ],
      },
      {
        name: '筹码集中价管理',
        foldName: '筹码表',
        path: '/trading-strategy/signal-strategies/chip-prices',
        permissionCodes: [PermissionCodes.STRATEGY_SIGNAL_READ],
      },
      {
        name: '关键价格管理',
        foldName: '关键价',
        path: '/trading-strategy/signal-strategies/key-prices',
        permissionCodes: [PermissionCodes.STRATEGY_SIGNAL_READ],
      },
    ],
  },
  {
    name: '执行策略管理',
    foldName: '执行策略',
    icon: 'DataAnalysis',
    path: '/trading-strategy/execution',
    permissionCodes: [PermissionCodes.STRATEGY_EXECUTION_READ],
    children: [
      {
        name: '仓位风控策略',
        foldName: '仓位风控',
        path: '/trading-strategy/execution/account-risk',
        permissionCodes: [PermissionCodes.STRATEGY_EXECUTION_READ],
      },
      {
        name: '建仓策略',
        foldName: '建仓策略',
        path: '/trading-strategy/execution/open-position',
        permissionCodes: [PermissionCodes.STRATEGY_EXECUTION_READ],
      },
      {
        name: '清仓策略',
        foldName: '清仓策略',
        path: '/trading-strategy/execution/close-position',
        permissionCodes: [PermissionCodes.STRATEGY_EXECUTION_READ],
      },
      {
        name: '做T策略',
        foldName: '做T策略',
        path: '/trading-strategy/execution/intraday-t',
        permissionCodes: [PermissionCodes.STRATEGY_EXECUTION_READ],
      },
    ],
  },
  {
    name: '做T约束',
    foldName: '做T约束',
    icon: 'DataAnalysis',
    path: '/trading-strategy/intraday-constraints',
    permissionCodes: [PermissionCodes.STRATEGY_INTRADAY_CONSTRAINT_READ],
    children: [
      {
        name: '买入风控约束策略',
        foldName: '买入约束',
        path: '/trading-strategy/intraday-constraints/buy-risk-block',
        permissionCodes: [PermissionCodes.STRATEGY_INTRADAY_CONSTRAINT_READ],
      },
      {
        name: '卖出趋势保护策略',
        foldName: '卖出趋势保护策略',
        path: '/trading-strategy/intraday-constraints/sell-trend-guard',
        permissionCodes: [PermissionCodes.STRATEGY_INTRADAY_CONSTRAINT_READ],
      },
    ],
  },
  {
    name: '模拟交易',
    foldName: '模拟交易',
    icon: 'Coin',
    path: '/sim-trading',
    permissionCodes: [PermissionCodes.SIM_TRADING_ACCOUNT_READ],
    children: [
      {
        name: '账号管理',
        foldName: '账号管理',
        path: '/sim-trading/accounts',
        permissionCodes: [PermissionCodes.SIM_TRADING_ACCOUNT_READ],
      },
      {
        name: '账号详情',
        foldName: '账号详情',
        path: '/sim-trading/account-detail',
        permissionCodes: [PermissionCodes.SIM_TRADING_ACCOUNT_READ],
      },
    ],
  },
  {
    name: '账号管理',
    foldName: '账号管理',
    icon: 'User',
    path: '/account-mgt',
    permissionCodes: [PermissionCodes.SYSTEM_USER_READ, PermissionCodes.SYSTEM_ROLE_READ],
    children: [
      {
        name: '用户管理',
        foldName: '用户管理',
        path: '/user-mgt',
        dataGuide: 'user-mgt',
        permissionCodes: [PermissionCodes.SYSTEM_USER_READ],
      },
      {
        name: '角色管理',
        foldName: '角色管理',
        path: '/account-mgt/roles',
        permissionCodes: [PermissionCodes.SYSTEM_ROLE_READ],
      },
    ],
  },
  {
    name: '日志管理',
    foldName: '日志管理',
    icon: 'Files',
    path: '/system/log-management',
    permissionCodes: [PermissionCodes.SYSTEM_LOG_READ],
  },
  {
    name: 'Dump版本管理',
    foldName: 'Dump版本',
    icon: 'Files',
    path: '/system/dump-snapshots',
    permissionCodes: [PermissionCodes.SYSTEM_DUMP_READ],
  },
  {
    name: '模糊搜索源设置',
    foldName: '搜索源设置',
    icon: 'Setting',
    path: '/system/stock-search-settings',
    permissionCodes: [PermissionCodes.SYSTEM_STOCK_SEARCH_SOURCE_READ],
  },
  {
    name: '股票本地查找表管理',
    foldName: '本地查找表',
    icon: 'DataBoard',
    path: '/system/stock-search-index-management',
    permissionCodes: [PermissionCodes.SYSTEM_STOCK_SEARCH_INDEX_READ],
  },
  {
    name: '富途openD订阅管理',
    foldName: '富途openD订阅管理',
    icon: 'DataAnalysis',
    path: '/futu-opend-subscriptions',
    permissionCodes: [PermissionCodes.SYSTEM_FUTU_SUBSCRIPTION_READ],
  },
]
