export const PermissionCodes = {
  SYSTEM_USER_READ: 'system:user:read',
  SYSTEM_USER_CREATE: 'system:user:create',
  SYSTEM_USER_UPDATE: 'system:user:update',
  SYSTEM_USER_DELETE: 'system:user:delete',
  SYSTEM_ROLE_READ: 'system:role:read',
  SYSTEM_ROLE_CREATE: 'system:role:create',
  SYSTEM_ROLE_UPDATE: 'system:role:update',
  SYSTEM_ROLE_DELETE: 'system:role:delete',
  SYSTEM_ROLE_ASSIGN: 'system:role:assign',
  SYSTEM_LOG_READ: 'system:log:read',
  SYSTEM_DUMP_READ: 'system:dump_snapshot:read',
  SYSTEM_STOCK_SEARCH_SOURCE_READ: 'system:stock_search_source:read',
  SYSTEM_STOCK_SEARCH_INDEX_READ: 'system:stock_search_index:read',
  SYSTEM_STOCK_SEARCH_INDEX_SYNC: 'system:stock_search_index:sync',
  SYSTEM_STOCK_SEARCH_INDEX_EXPORT: 'system:stock_search_index:export',
  SYSTEM_FUTU_SUBSCRIPTION_READ: 'system:futu_subscription:read',
  STRATEGY_SIGNAL_READ: 'strategy:signal:read',
  STRATEGY_SIGNAL_WRITE: 'strategy:signal:write',
  STRATEGY_EXECUTION_READ: 'strategy:execution:read',
  STRATEGY_EXECUTION_WRITE: 'strategy:execution:write',
  STRATEGY_INTRADAY_CONSTRAINT_READ: 'strategy:intraday_constraint:read',
  STRATEGY_INTRADAY_CONSTRAINT_WRITE: 'strategy:intraday_constraint:write',
  SIM_TRADING_ACCOUNT_READ: 'sim_trading:account:read',
  SIM_TRADING_ACCOUNT_WRITE: 'sim_trading:account:write',
  STOCK_POOL_STRATEGY_READ: 'stock_pool:strategy:read',
  STOCK_POOL_SELF_SELECTED_READ: 'stock_pool:self_selected:read',
}
